version: '3'
services:
  redis:
    image: redis
    ports:
      - "8701:6379"

  mysql:
    image: mysql:5.7
    ports:
      - "8702:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  server:
    image: keratin/authn-server:latest
    ports:
      - "7002:3000"
    environment:
      - APP_DOMAINS
      - AUTHN_URL
      - SECRET_KEY_BASE
      - DATABASE_URL=sqlite3://localhost/dev
      - REDIS_URL=redis://redis:6379/11
    depends_on:
      - redis
